### ISSUE TITLE
prefer accessing ENV directly from code

### ISSUE THREAD

**Issue by jjulian** [kingishb/good-bike-weather#1]
By accessing your secrets and passing on the command-line, there is a small chance they can leak in a shared virtual machine. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by kingishb** [comment]
Thanks! I inadvertently fixed this, when I broke my ankle and rewrote this in Rust for fun (since I could not bike). But! Hopefully you're good with your fork as well.
